### PR TITLE
bp miner rebalance, I hope people will like it

### PR DESCRIPTION
**Pull request by maksxpl**
## About The Pull Request

image

## Changelog
:cl:
balance: Bluespace miner now costs 5 refined bluespace crystals
balance: Bluespace miner research now requires alien tech research node
/:cl:

### CODE REVIEW

**Comment by Dexxiol** [comment]
please no

**Comment by AnonChangechong** [comment]
Maks is drinking tears of solo palyers...

**Comment by maksxpl** [comment]
_**P L E A S E  Y E S**_

**Comment by Castone001** [comment]
Dumbest idea yet. Rip to 1 and a half hours every round start before you can do what you actually want to do.

**Pull request merged**
