### PR TITLE
kilostation perma expansion

### PR DESCRIPTION
**Pull request by RanDoomGuy21**
aaaaaaaaaaaaaaa

## About The Pull Request
I decided to snatch some things from TG's current kilo.

## Why It's Good For The Game

Perma isnt boring now (its only kilo)

## Changelog
:cl:
add: Expanded Kilo Perma
add: Jerry in cargo and a small outpost with hivelords in it
del: Old stinky perma is no more
fix: Moved the blast door buttons in atmos from the windows so you can actually use them
/:cl:

### CODE REVIEW

**Comment by RanDoomGuy21** [comment]
_oh you have got to be fuckin me_

**Comment by RanDoomGuy21** [comment]
and fixed
never felt more proud of myself

**Comment by AnonChangechong** [comment]
Will check it out soon-ish and probably merge it asap

**Comment by maksxpl** [comment]
@AnonChangechong did you check the map if everything looks good?

@RanDoomGuy21 I'll apricate if you will rename PR to some nicer way than aaaaaaaaaAAAAAAAAAAAAAAAAAAAAAAA

**Comment by AnonChangechong** [comment]
Not yet

**Review by AnonChangechong — CHANGES_REQUESTED** [review]
First of all, 
Perma redesign is a big nono due to shared opinion of it being straight ugly, too big for kilo and as host said "having many logistical problems". So this is to be removed.

Outpost is nice and can stay.

But the biggest sin is that you didnt edited map in the code so nostra changes present on kilo are being deleted with this pull.

Feel free to add outpost to map in code so you dont delete existing changes.

**Comment by RanDoomGuy21** [comment]
👌

**Comment by RanDoomGuy21** [comment]
should be easy to do, the perma is taken from the current TG kilo

**Pull request closed without merging**
