### PR TITLE
terror spiders are no more

### PR DESCRIPTION
**Pull request by maksxpl**
## Why It's Good For The Game

Coders now won't have to give a fuck about linter error

## Changelog
:cl:
del: Deleted terror spiders
/:cl:

### CODE REVIEW

**Comment by AnonChangechong** [comment]
it wont work coz byond, enjoy

**Comment by maksxpl** [comment]
> it wont work coz byond, enjoy

fuck you too

**Comment by AnonChangechong** [comment]
Thats what byond said

**Comment by maksxpl** [comment]
> Thats what byond said

I know where you live

**Comment by AnonChangechong** [comment]
another commit another error another laugh for byond machine spirit

**Pull request merged**
